// <auto-generated />
using System;
using HCLSWebAPI.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HCLSWebAPI.Migrations
{
    [DbContext(typeof(DBContextt))]
    [Migration("20241002075604_ProjectHCLS")]
    partial class ProjectHCLS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HCLSWebAPI.Models.AdminTypes", b =>
                {
                    b.Property<int>("AdminTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdminTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminTypeId");

                    b.ToTable("AdminTypes");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Admins", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.HasIndex("AdminTypeId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Department", b =>
                {
                    b.Property<int>("DeptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptNo");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Doctor", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Assigned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<int>("DocSpecId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Logged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DocId");

                    b.HasIndex("DeptNo");

                    b.HasIndex("DocSpecId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.DoctorSpecialization", b =>
                {
                    b.Property<int>("DocSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocSpecId");

                    b.ToTable("DoctorSpecialization");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Helper", b =>
                {
                    b.Property<int>("HelpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Assigned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Logged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HelpId");

                    b.HasIndex("DeptNo");

                    b.ToTable("Helper");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Logged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LabId");

                    b.HasIndex("DeptNo");

                    b.ToTable("Lab");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("BillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CameForDiagnosist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocId")
                        .HasColumnType("int");

                    b.Property<int>("DocSpecId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HelpId")
                        .HasColumnType("int");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecpId")
                        .HasColumnType("int");

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpComingVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientId");

                    b.HasIndex("DocId");

                    b.HasIndex("DocSpecId");

                    b.HasIndex("HelpId");

                    b.HasIndex("LabId");

                    b.HasIndex("RecpId");

                    b.HasIndex("StatId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.PatientStatus", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("StatName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatId");

                    b.ToTable("PatientStatus");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Receptionist", b =>
                {
                    b.Property<int>("RecpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Logged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecpId");

                    b.HasIndex("DeptNo");

                    b.ToTable("Receptionist");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Admins", b =>
                {
                    b.HasOne("HCLSWebAPI.Models.AdminTypes", "AdminTypes")
                        .WithMany("Admins")
                        .HasForeignKey("AdminTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminTypes");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Doctor", b =>
                {
                    b.HasOne("HCLSWebAPI.Models.Department", "Department")
                        .WithMany("Doctor")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCLSWebAPI.Models.DoctorSpecialization", "DoctorSpecialization")
                        .WithMany("Doctor")
                        .HasForeignKey("DocSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DoctorSpecialization");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Helper", b =>
                {
                    b.HasOne("HCLSWebAPI.Models.Department", "Department")
                        .WithMany("Helper")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Lab", b =>
                {
                    b.HasOne("HCLSWebAPI.Models.Department", "Department")
                        .WithMany("Lab")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Patient", b =>
                {
                    b.HasOne("HCLSWebAPI.Models.Doctor", "Doctor")
                        .WithMany("Patient")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCLSWebAPI.Models.DoctorSpecialization", "DoctorSpecialization")
                        .WithMany("Patient")
                        .HasForeignKey("DocSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCLSWebAPI.Models.Helper", "Helper")
                        .WithMany("Patient")
                        .HasForeignKey("HelpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCLSWebAPI.Models.Lab", "Lab")
                        .WithMany("Patient")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCLSWebAPI.Models.Receptionist", "Receptionist")
                        .WithMany("Patient")
                        .HasForeignKey("RecpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCLSWebAPI.Models.PatientStatus", "PatientStatus")
                        .WithMany("Patient")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("DoctorSpecialization");

                    b.Navigation("Helper");

                    b.Navigation("Lab");

                    b.Navigation("PatientStatus");

                    b.Navigation("Receptionist");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Receptionist", b =>
                {
                    b.HasOne("HCLSWebAPI.Models.Department", "Department")
                        .WithMany("Receptionist")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.AdminTypes", b =>
                {
                    b.Navigation("Admins");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Department", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Helper");

                    b.Navigation("Lab");

                    b.Navigation("Receptionist");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Doctor", b =>
                {
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.DoctorSpecialization", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Helper", b =>
                {
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Lab", b =>
                {
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.PatientStatus", b =>
                {
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HCLSWebAPI.Models.Receptionist", b =>
                {
                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
